#ifndef ENV_H
#define ENV_H
#define ROBOT_VERSION_STRING "CRE/CYGNUS:"

#define ENABLE_DRIVETRAIN
#define ENABLE_CLIMBER
#define ENABLE_SHOOTER
#define ENABLE_CONTROL_PANEL_MANIPULATOR
#define ENABLE_VISION

#endif // ENV_H
